const mapping = {
  "hero 1": "characterName",
  "hero 2": "notes_part1",
  "hero 3": "notes_part2",
  "STR_value": "str",
  "DEX_value": "dex",
  "INT_value": "int",
  "WIL_value": "wil",
  "arcana": "arcana",
  "examination": "examination",
  "finesse": "finesse",
  "influence": "influence",
  "insight": "insight",
  "lore": "lore",
  "might": "might",
  "naturecraft": "naturecraft",
  "perception": "perception",
  "stealth": "stealth",
  "level": "level",
  "sublcass": "subclass",
  "prof": "proficiencies",
  "size": "size",
  "speed": "speed",
  "init": "initiative",
  "defense": "armor",
  "HD current": "hitDice",
  "HP temp": "tempHp",
  "HP current": "hpCurrent",
  "HP max": "hpMax",
  "mana current": "classResource1Current",
  "mana max": "classResource1Max",
  "spell tier": "spellTier",
  "reactions and utility": "features",
  "actions and attacks": "spells",
}
